#Database connection configuration
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  #Show formated SQL statements
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  #Domain SQL init script configuration
  sql:
    init:
      mode: always
      data-locations: classpath:scripts/init-script.sql

  #Authorization server configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}

#User API port
server:
  port: 8080
  ssl:
    enabled: false

#SpringDoc configuration
springdoc:
  api-docs:
    enabled: true
    version: openapi_3_1
    path: /forumhub.io/api/v1/openapi-prod.yaml
  swagger-ui:
    enabled: true
    url: openapi-prod.yaml
    path: /forumhub.io/api/v1/swagger-ui.html
    oauth:
      use-basic-authentication-with-access-code-grant: true
      use-pkce-with-authorization-code-grant: true
      client-id: ${OAUTH2_USER_CLIENT_ID}
      client-secret: ${OAUTH2_USER_PASSWORD}
    displayRequestDuration: true