#Database connection configuration
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  #Show formated SQL statements
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  #Authorization server configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}

#User API port
server:
  port: ${PORT}
  ssl:
    enabled: false

#SpringDoc configuration
springdoc:
  api-docs:
    enabled: true
    version: openapi_3_1
    path: ${PATH_OPEN_API}
  swagger-ui:
    enabled: true
    url: openapi.yaml
    path: ${PATH_SWAGGER_UI}
    oauth:
      use-basic-authentication-with-access-code-grant: true
      use-pkce-with-authorization-code-grant: true
      client-id: ${OAUTH2_USER_CLIENT_ID}
      client-secret: ${OAUTH2_USER_PASSWORD}