#Database connection configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/PSQLDEVBR
    username: hub
    password: forumhub
    driver-class-name: org.postgresql.Driver

  #Show formated SQL statements
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  #Domain SQL init script configuration
  sql:
    init:
      mode: always
      data-locations: classpath:scripts/init-script.sql

  #Authorization server configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8082

#User API port
server:
  port: 8081

#SpringDoc configuration
springdoc:
  api-docs:
    enabled: true
    version: openapi_3_1
    path: /forumhub.io/api/v1/openapi.yaml
  swagger-ui:
    enabled: true
    url: openapi-dev.yaml
    path: /forumhub.io/api/v1/swagger-ui.html
    oauth:
      use-basic-authentication-with-access-code-grant: true
      use-pkce-with-authorization-code-grant: true
      client-id: hub-user
      client-secret: aHViLXVzZXI6ZWJjNTFlNGItMjQxOC00MTNkLTlhNWUtNDU2Yzk1YjQ3Yzcz
    displayRequestDuration: true