#Database connection configuration
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  #Show formated SQL statements
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  #Flyway configuration
  flyway:
    default-schema: ${POSTGRES_USER}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    baseline-on-migrate: true
    enabled: true

  #Authorization server configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}

      #Client User API registration
      client:
        registration:
          forumhub-user:
            provider: ${AUTH_SERVER_PROVIDER}
            client-id: ${USER_CLIENT_ID}
            client-secret: ${USER_CLIENT_SECRET}
            client-authentication-method: ${USER_CLIENT_AUTHENTICATION_METHOD}
            authorization-grant-type: ${USER_CLIENT_AUTHORIZATION_GRANT_TYPE}
            client-name: ${USER_CLIENT_NAME}
            scope: ${USER_CLIET_SCOPE}
        provider:
          auth-server:
            issuer-uri: ${ISSUER_URI}

#Topic API port
server:
  port: 8080

#User client URL
forumhub:
  client:
    user:
      schema: ${USER_SERVER_PROTOCOL}
      host: ${USER_SERVER_HOST}
      port: ${USER_SERVER_PORT}

#SpringDoc configuration
springdoc:
  api-docs:
    enabled: true
    version: openapi_3_1
    path: /forumhub.io/api/v1/openapi.yaml
  swagger-ui:
    enabled: true
    url: openapi.yaml
    path: /forumhub.io/api/v1/swagger-ui.html
    oauth:
      use-basic-authentication-with-access-code-grant: true
      use-pkce-with-authorization-code-grant: true
      client-id: hub-topic
      client-secret: aHViLXRvcGljOmNmZjM3MWJmLWFhNDYtNDNjOC04ODdlLTI4MmJjZDM3ZjEzNw==