#Database connection configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/PSQLDEVBR
    username: hub
    password: forumhub
    driver-class-name: org.postgresql.Driver

  #Show formated SQL statements
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  #Flyway configuration
  flyway:
    default-schema: hub
    user: hub
    password: forumhub
    baseline-on-migrate: true
    enabled: true

  #Authorization server configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8082

      #Client User API registration
      client:
        registration:
          forumhub-user:
            provider: auth-server
            client-id: hub-user
            client-secret: aHViLXVzZXI6ZWJjNTFlNGItMjQxOC00MTNkLTlhNWUtNDU2Yzk1YjQ3Yzcz
            client-authentication-method: client_secret_basic
            authorization-grant-type: client_credentials
            client-name: forumhub-user
            scope: myuser:read
        provider:
          auth-server:
            issuer-uri: http://127.0.0.1:8082

#Topic API port
server:
  port: 8080

#User client URL
forumhub:
  client:
    user:
      schema: http
      host: 127.0.0.1
      port: 8081
      path: /forumhub.io/api/v1/users/summary-info

#SpringDoc configuration
springdoc:
  api-docs:
    enabled: true
    version: openapi_3_1
    path: /forumhub.io/api/v1/openapi.yaml
  swagger-ui:
    enabled: true
    url: openapi.yaml
    path: /forumhub.io/api/v1/swagger-ui.html
    oauth:
      use-basic-authentication-with-access-code-grant: true
      use-pkce-with-authorization-code-grant: true
      client-id: hub-topic
      client-secret: aHViLXRvcGljOmNmZjM3MWJmLWFhNDYtNDNjOC04ODdlLTI4MmJjZDM3ZjEzNw==
