CREATE TABLE profile (
    profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    profile VARCHAR(50) NOT NULL UNIQUE CHECK (profile IN ('ADM','MOD','BASIC')),
    PRIMARY KEY (profile_id)
);

CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    username VARCHAR(20) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    "password" VARCHAR(255) NOT NULL,
    is_account_non_expired BOOLEAN DEFAULT TRUE,
    is_account_non_locked BOOLEAN DEFAULT TRUE,
    is_credentials_non_expired BOOLEAN DEFAULT TRUE,
    is_enabled BOOLEAN DEFAULT TRUE,
    profile_id BIGINT,
    PRIMARY KEY (user_id),
    CONSTRAINT FK_PROFILE_USERS FOREIGN KEY (profile_id) REFERENCES profile(profile_id)
);

CREATE TABLE course (
    course_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(255) NOT NULL UNIQUE,
    category VARCHAR(50) NOT NULL CHECK (category IN ('JAVA','C','CPLUSPLUS','CSHARP','GOLANG','COMPUTATION','QA')),
    PRIMARY KEY (course_id)
);

CREATE TABLE topic (
    topic_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(200) NOT NULL,
    question VARCHAR(255) NOT NULL,
    status CHAR(10) DEFAULT 'UNSOLVED' CHECK (status IN ('SOLVED', 'UNSOLVED')),
    created_at TIMESTAMP(6) WITH TIME ZONE,
    user_id BIGINT,
    course_id BIGINT,
    PRIMARY KEY (topic_id),
    CONSTRAINT FK_USERS_TOPIC FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT FK_COURSE_TOPIC FOREIGN KEY (course_id) REFERENCES course(course_id)
);

INSERT INTO profile (profile) VALUES ('ADM');
INSERT INTO profile (profile) VALUES ('MOD');
INSERT INTO profile (profile) VALUES ('BASIC');

INSERT INTO "users"
(FIRST_NAME, LAST_NAME, USERNAME, EMAIL, PASSWORD, PROFILE_ID)
VALUES('adm', 'adm', 'adm', 'adm@email.com', '$2a$10$dKvyjxi6gbqvGWzchu0dDedZsvTzDvhKp6rf5xVBlTg62pwtZwfCO', 1);